### ISSUE TITLE
Widget ++

### ISSUE THREAD

**Issue by VB10** [CanArslanDev/simple_animation_progress_bar#1]
https://github.com/CanArslanDev/simple_animation_progress_bar/blob/22f1fd52a96307a642bbe90fcb4c20c917f4a6b9/lib/src/simple_animation_container.dart#L96

-- widgetlarını function olarak yapma extract widget diyerek ayır
- ratio = 0 yazan kodu build içinden çıkartıp ınıt state yapbilrisin burada analadığım kadaıryla sürekli bir dönüş bekleniyor bunun için timer yapaiblirisn veya sürekli biribrni çağıran bir while döngüsü ile eşityelybirisn
- bu tarz basit işlerde dahi olsa setstate yerine valunotifer kullanbilrisn
- her methodunun ve veriabline public doc yaz ki başkası anlasın
- row ve colum birden fazla widget varsa kullan
- very good analsis kullan
- method vs yapsan dahi burada type döndürmeyi unutma

**Comment by CanArslanDev** [comment]
Çok teşekkür ederim Veli abi, bu şekilde sektörün içinden birisinden yorum almak gerçekten beni çok mutlu etti, en kısa zamanda bunları düzeltip yeni patch olarak yayınlayacağım.

**Comment by CanArslanDev** [comment]
Tekrardan Merhaba Veli Hocam,
Öncelikle bana verdiğiniz önerilerden dolayı tekrar teşekkür etmek istiyorum. Söylediğiniz önerileri göz önünde bulundurarak paketin 1.2.0 güncellemesini yayınlamış bulunmaktayım. Tek takıldığım yer very good analysis kısmında paketi tam olarak nasıl ve ne amaçla kullanacağımı tam kavrayamadığımdan dolayı onu bu güncellemeye dahil etmedim fakat sonraki güncellemelerde daha detaylı araştırarak ekleyeceğim.
