### ISSUE TITLE
Library not compiling with AGP8 (Gradle 8)

### ISSUE THREAD

**Issue by marc7garcia** [CanArslanDev/simple_animation_progress_bar#2]
When trying to compile Flutter project with simple-animation-progress-bar 1.6.0, compiler says the following:

A problem occurred configuring project ':simple_animation_progress_bar'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

Please, can you upgrade the library with AGP8 compatibility?

Thank you so much! :)

**Comment by CanArslanDev** [comment]
Hello,
First of all, thank you for your feedback.
I published the new version of the package by making changes regarding your error, added a namespace field and made a few changes to the SDK version.
I hope your error will be resolved, please, after the 1.7.0 version is released, you can go to the pubspec.yaml file in your project and replace it with the ```simple_animation_progress_bar: "^1.7.0"``` version to start using the new version.

Thanks,
Can

**Comment by marc7garcia** [comment]
Hi @CanArslanDev !
First of all, thank you so much for your fast response :)
I've tried the new version 1.7.0 and it also fails. This is the compilation error:

Execution failed for task ':simple_animation_progress_bar:processDebugManifest'.
> A failure occurred while executing com.android.build.gradle.tasks.ProcessLibraryManifest$ProcessLibWorkAction
   > Incorrect package="com.example.simple_aniatiom_progress_bar.simple_animation_progress_bar" found in source AndroidManifest.xml: /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.7.0/android/src/main/AndroidManifest.xml.
     Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
     Recommendation: remove package="com.example.simple_aniatiom_progress_bar.simple_animation_progress_bar" from the source AndroidManifest.xml: /Users/marc/.pub-cache/hosted/pub.dev/simple_animation_progress_bar-1.7.0/android/src/main/AndroidManifest.xml.

Please, can you review it?

Thank you so much!

Marc.
